# Generated by Django 3.2.6 on 2022-11-16 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('release_data', models.DateField()),
                ('vote_average', models.FloatField()),
                ('overview', models.TextField()),
                ('genre', models.CharField(max_length=50)),
                ('poster_path', models.CharField(max_length=200)),
                ('actor', models.CharField(max_length=150)),
                ('director', models.CharField(max_length=150)),
                ('runnig_time', models.CharField(max_length=150)),
            ],
        ),
    ]
